project_name : day-04-SeqAn
author: "Hang Mai Anh Vo, Baptiste Roizard"
date: 2025.05.09

output_dir_path: "results"
create_input_tsv: false
window_size: 100
samples: "config/samples.tsv"
reference_genome: "resources/sequence.fasta"
