project_name : day-05-SeqAn
author: "Hang Mai Anh Vo, Baptiste Roizard"
date: 2025.06.06

output_dir_path: "results"
create_input_tsv: false
fastp_flags: "--detect_adapter_for_pe --thread 4 --qualified_quality_phred 15 --length_required 50" # personalize

samples: "config/samples.tsv"
ref_genome: "" # resources/Homo_sapiens.GRCh38.dna.chromosome.22.fa.gz
annotation: "" # resources/Homo_sapiens.GRCh38.114.chr.gtf.gz


