project_name : day-05-SeqAn
author: "Hang Mai Anh Vo, Baptiste Roizard"
date: 2025.06.06

output_dir_path: "results"
create_input_tsv: false
fastp_flags: "--detect_adapter_for_pe --thread 4 --qualified_quality_phred 15 --length_required 50" # personalize, other:  --cut_front --cut_tail --cut_window_size 4 --cut_mean_quality 20

samples: "config/samples_set1.tsv" # or "config/samples_set2.tsv"
short_reads: true
long_reads: true
blacklist_file: "config/sample_blacklist.tsv" # optional, if you want to exclude some samples from the analysis. User edited file.
kraken_db: "data/kraken2_db"
contaminant_fasta: "resources/contaminants.fasta"

bakta_db_download: true
bakta_db_path: "resources/bakta_db/db-light"
bacteria_odb10: "resources/bacteria_odb10" #lineage gene set

busco_db_download: true
busco_db_path: "resources/busco"
bacteria_odb10: "bacteria_odb10"

run_mlst: true
run_resistance: true
run_virulence: true
# run_plasmid: true
run_plasmidfinder: false

mlst_db_path: "" # empty for default database, or manually install to "resources/mlst_db"
mlst_scheme: "klebsiella" # can change based on your data (e.g., "salmonella", "e_coli", etc.)
abricate_db_path_card: "resources/abricate_db"
abricate_db_path_vfdb: "resources/abricate_db"
# mob_suite_db_path: "resources/mob_suite_db"
plasmidfinder_db_path: "resources/plasmidfinder_db"






