import os
from pathlib import Path
import pandas as pd

# load samples into table

configfile : "./config/config.yaml"
samples = pd.read_csv(config["samples"], index_col = "sample", sep ='\t')

rule all:
    input:
        expand(
            f"{config['output_dir_path']}/assembly_qc/{{sample}}_{{read_number}}",
            sample=samples.index,
            read_number=["1", "2"]
        ),
        f"{config['output_dir_path']}/phylogeny/all_samples.tree.png",
        f"{config['output_dir_path']}/variability/all_samples_var_plot.png",
        f"{config['output_dir_path']}/variability/all_samples_windows_var.txt"

include: "rules/fastp.smk"
include: "rules/spades.smk"
include: "rules/quast.smk"
include: "rules/align_assembly.smk"
include: "rules/call_consensus.smk"
include: "rules/concat_consensus.smk"
include: "rules/mafft.smk"
include: "rules/iqtree.smk"
include: "rules/vis.smk"
include: "rules/var.smk"