project_name : day-03-SeqAn
author: "Hang Mai Anh Vo, Baptiste Roizard"
date: 2025.05.09

ref: "data/reference.fa"
output_dir_path: "results"
create_input_tsv: false

samples: "config/samples.tsv"

##### Bowtie2 Params #####
bowtie2:
  N: 1
  L: 30
  D: 15
  R: 2

##### Trimmomatic Params #####
adapter_file: "resources/TruSeq2-PE.fa"
trimmo_threads: 4
seed_mismatches: 2
palindromeClipThreshold: 30
simpleClipThreshold: 10
leading: 3
trailing: 3
sliding_window_lb: 4
sliding_window_ub: 15
minlen: 36